/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hair;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_cus = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cusid = new javax.swing.JTextField();
        cusname = new javax.swing.JTextField();
        custel = new javax.swing.JTextField();
        cusadd = new javax.swing.JTextField();
        cusemail = new javax.swing.JTextField();
        jb_save = new javax.swing.JButton();
        jb_edit = new javax.swing.JButton();
        jb_res = new javax.swing.JButton();
        jb_edit1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer");

        tb_cus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_cus.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                tb_cusAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tb_cusAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tb_cus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_cusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_cus);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("CustomerName :");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("TelNumber :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Address :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Email :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("CustomerID :");

        cusid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cusid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusidActionPerformed(evt);
            }
        });

        cusname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        custel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cusadd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cusemail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cusemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusemailActionPerformed(evt);
            }
        });

        jb_save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jb_save.setText("Save");
        jb_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_saveActionPerformed(evt);
            }
        });

        jb_edit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jb_edit.setText("Update");
        jb_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_editActionPerformed(evt);
            }
        });

        jb_res.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jb_res.setText("Clear");
        jb_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_resActionPerformed(evt);
            }
        });

        jb_edit1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jb_edit1.setText("Back");
        jb_edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_edit1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem1.setText("Login/Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem2.setText("Product");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem3.setText("Insert Product");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem5.setText("Check Order");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem4.setText("บันทึกการขาย");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cusid, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cusname, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cusadd, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cusemail, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jb_edit)
                                    .addComponent(jb_save))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_res)
                                    .addComponent(jButton1))))
                        .addContainerGap(78, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_edit1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cusid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cusname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cusadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cusemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_save)
                            .addComponent(jb_res))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_edit)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_edit1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cusemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusemailActionPerformed

    private void jb_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_saveActionPerformed
        DefaultTableModel model = (DefaultTableModel) tb_cus.getModel();
        Vector vec = new Vector();
        Connection connect =null;
        Statement s =null;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connect = DriverManager.getConnection("jdbc:sqlserver://localhost;databaseName=RumRuay_Beauty;user=sa;password=19082012");
            s = connect.createStatement();
            

            String sql = "INSERT INTO Customer(CustomerID,CustomerName,TelNumber,Address,Email)"
                    + "VALUES ('"+cusid.getText()+"','"
                    +cusname.getText()+"','"
                    +custel.getText()+"','"
                    +cusadd.getText()+"','"
                    +cusemail.getText()+"')";
            
                    s.execute(sql);

                JOptionPane.showMessageDialog(this, "Successfully.");


        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            e.printStackTrace();
        }
            try{
                 if(s != null){
                  s.close();
                  connect.close();
            }
            }catch (SQLException e){
                      System.out.println(e.getMessage());
                      e.printStackTrace();;
                      }
            getContentPane().add(jb_save);
        vec.add(cusid.getText());
        vec.add(cusname.getText());
        vec.add(custel.getText());
        vec.add(cusadd.getText());
        vec.add(cusemail.getText());
        model.addRow(vec);
    }//GEN-LAST:event_jb_saveActionPerformed

    private void cusidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusidActionPerformed
////        for (int i = 0; i < cusid.getRowCount(); i++){
////            if(name.getSelectedItem().toString().equals(tbproduct.getValueAt(i,0))){
////               System.out.println("รายการอาหารซ้ำกัน");
////                return true; 
//        for(i=0; i < cusid.getText(); i++){
//            if(cusid.getSelectedText().toString())
//            }  
//
            
    }//GEN-LAST:event_cusidActionPerformed

    private void tb_cusAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tb_cusAncestorAdded
        DefaultTableModel model = (DefaultTableModel)tb_cus.getModel();
        model.addColumn("CustomerID");
        model.addColumn("CustomerName");
        model.addColumn("TelNumber");
        model.addColumn("Address");
        model.addColumn("Email");
        Connection connect =null;
        Statement s =null;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connect = DriverManager.getConnection("jdbc:sqlserver://localhost;databaseName=RumRuay_Beauty;user=sa;password=19082012");
            s = connect.createStatement();
            String sql ="SELECT * FROM Customer";
            ResultSet result = s.executeQuery(sql);
            int row=0;
            while((result!=null) && (result.next()))
            {
                model.addRow(new Object[0]);
                model.setValueAt(result.getString("CustomerID"), row, 0);
                model.setValueAt(result.getString("CustomerName"), row, 1);
                model.setValueAt(result.getString("TelNumber"), row, 2);
                model.setValueAt(result.getString("Address"), row, 3);
                model.setValueAt(result.getString("Email"), row, 4);
                row++;
            }
            result.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            e.printStackTrace();
        }
        try{
            if(s != null){
            s.close();
            connect.close();
        }
        }catch(SQLException e){
            e.printStackTrace();
        }

        
    }//GEN-LAST:event_tb_cusAncestorAdded

    private void jb_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_resActionPerformed
        cusid.setText("");
        cusname.setText("");
        custel.setText("");
        cusadd.setText("");
        cusemail.setText("");

    }//GEN-LAST:event_jb_resActionPerformed

    private void jb_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_editActionPerformed
        DefaultTableModel model = (DefaultTableModel)tb_cus.getModel();
        Vector vec = new Vector();
        int index = tb_cus.getSelectedRow();
        int row=tb_cus.getSelectedColumn();
        Connection connect =null;
        Statement s =null;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connect = DriverManager.getConnection("jdbc:sqlserver://localhost;databaseName=RumRuay_Beauty;user=sa;password=19082012");
            s = connect.createStatement();
            

            String sql = "UPDATE Customer SET CustomerName = '"+cusname.getText()+"' "+
                    ",TelNumber = '"+custel.getText()+"' "+
                    ",Address = '"+cusadd.getText()+"' "+
                    ",Email = '"+cusemail.getText()+"' "+ 
                   " WHERE CustomerID = '"+cusid.getText()+"' ";
                    s.execute(sql);


                        JOptionPane.showMessageDialog(this, "Successfully.");


           model.setValueAt(cusname.getText().toString(),index , 1);
           model.setValueAt(custel.getText().toString(), index, 2);
           model.setValueAt(cusadd.getText().toString(), index, 3);
           model.setValueAt(cusemail.getText().toString(), index, 4);


        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            e.printStackTrace();
        }
            try{
                 if(s != null){
                  s.close();
                  connect.close();
            }
            }catch (SQLException e){
                      System.out.println(e.getMessage());
                      e.printStackTrace();;
                      }

//           model.setValueAt(cusname.getText().toString(),index , 1);
//           model.setValueAt(custel.getText().toString(), index, 2);
//           model.setValueAt(cusadd.getText().toString(), index, 3);
//           model.setValueAt(cusemail.getText().toString(), index, 4);
//            
    }//GEN-LAST:event_jb_editActionPerformed

    private void tb_cusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_cusMouseClicked
        DefaultTableModel model = (DefaultTableModel)tb_cus.getModel();
        cusid.setText(model.getValueAt(tb_cus.getSelectedRow(),0).toString());
        cusname.setText(model.getValueAt(tb_cus.getSelectedRow(),1).toString());
        custel.setText(model.getValueAt(tb_cus.getSelectedRow(),2).toString());   
        cusadd.setText(model.getValueAt(tb_cus.getSelectedRow(),3).toString()); 
        cusemail.setText(model.getValueAt(tb_cus.getSelectedRow(),4).toString()); 
    }//GEN-LAST:event_tb_cusMouseClicked

    private void jb_edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_edit1ActionPerformed
        Choose form = new Choose();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jb_edit1ActionPerformed

    private void tb_cusAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tb_cusAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_cusAncestorMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel)tb_cus.getModel();
        int index = tb_cus.getSelectedRow();
        String id = tb_cus.getValueAt(index, 0).toString();
//        Vector vec = new Vector();
        Connection connect =null;
        Statement s =null;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connect = DriverManager.getConnection("jdbc:sqlserver://localhost;databaseName=RumRuay_Beauty;user=sa;password=19082012");
            s = connect.createStatement();

            String sql = "DELETE FROM Customer WHERE CustomerID = '"+id+"'";
            s.execute (sql);
        

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            e.printStackTrace();
        }
            try{
                 if(s != null){
                  s.close();
                  connect.close();
            }
            }catch (SQLException e){
                      System.out.println(e.getMessage());
                      e.printStackTrace();
                      }
                    if(index < 0){
            JOptionPane.showMessageDialog(null, "Please select record for Delete.");
        }else{           
            Object[] options = {"Yes","No"};
            int n = JOptionPane.showOptionDialog(null, 
                    "Do you want to Delete data?",
                    "Confirm to Delete?",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE,null,options,
                    options[1]);

            if(n == 0){
                
                     JOptionPane.showMessageDialog(null, "Delete Data Successfully");
                     model.removeRow(index);
        }
                };
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Report form = new Report();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Product_Pay form = new Product_Pay();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        product form = new product();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Login form = new Login();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
            Orders form = new Orders();
            form.setVisible(true);
            this.dispose();    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cusadd;
    private javax.swing.JTextField cusemail;
    private javax.swing.JTextField cusid;
    private javax.swing.JTextField cusname;
    private javax.swing.JTextField custel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_edit;
    private javax.swing.JButton jb_edit1;
    private javax.swing.JButton jb_res;
    private javax.swing.JButton jb_save;
    private javax.swing.JTable tb_cus;
    // End of variables declaration//GEN-END:variables
}
